name: Update Policy Catalog
on:
  push:
    paths:
      - 'Policies/**/*.json'
    branches:
      - main
  workflow_dispatch:

jobs:
  update-catalog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Generate Policy Catalog
        run: |
          python .github/scripts/generate_catalog.py
        
      - name: Commit and Push if Changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Policies/latest.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "🥷 Update policy catalog" && git push)
